version: '3.9'
services:
  charon:
    image: charon:${BUILD_TAG}
    build: ../
    volumes:
      - ${SHARED_DIR}/charon/data:/data
    command: -config.file /data/cfg.yaml -target all -downloader.temp-dir /data/downloader
    restart: unless-stopped
    depends_on:
      - minio
      - consul
      - postgres
      - nats

  minio:
    image: minio/minio
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
      - ${SHARED_DIR}/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
  consul:
    image: consul
    ports:
      - "8500:8500"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    environment:
      CONSUL_HTTP_TOKEN: ${CONSUL_HTTP_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
  nats:
    image: nats
    ports:
      - "4222:4222"
    environment:
      NATS_SERVER_USERNAME: ${NATS_USER}
      NATS_SERVER_PASSWORD: ${NATS_PASSWORD}
    healthcheck:
      test: ["CMD", "nats", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped